version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  lesson5:
   image: lesson5
   build:
     context: .
   environment:
     DB_URL: "jdbc:postgresql://postgres:5432/postgres"
   ports:
     - "8080:8080"
   depends_on:
     - postgres
volumes:
  data_postgres: